resolver: lts-17.4

packages:
- ./

extra-deps:
# - xmonad-0.15
- url: https://github.com/wygulmage/xmonad/archive/k.tar.gz
- X11-1.9.2

nix:
   packages:
   - zlib
   - xorg.libX11
   - xorg.libXrandr
   - xorg.libXScrnSaver
   - xorg.libXext
   - xorg.libXft
   - pkg-config

